import { addDesignOption, addGarmentType, addMeasurementField } from "@/app/actions/garment-management";
import { db, garmentDesignCategories, garmentDesignOptions, garmentMeasurementFields, garmentTypes } from "@/lib/db";
import { asc } from "drizzle-orm";
import { cookies } from "next/headers";
import { getLocale, getTranslations } from "@/lib/i18n";
import { shopSettings } from "@/lib/db";
import { SettingsForm } from "./settings-form";

export default async function SettingsPage() {
  const locale = getLocale((await cookies()).get("tailor_locale")?.value);
  const t = getTranslations(locale);
  const [types, fields, categories, options, shop] = await Promise.all([db.select().from(garmentTypes).orderBy(asc(garmentTypes.sortOrder)), db.select().from(garmentMeasurementFields), db.select().from(garmentDesignCategories), db.select().from(garmentDesignOptions), db.select().from(shopSettings).then((rows) => rows[0])]);
  const help = locale === "en" ? "Manage shop settings, garment measurements, and design choices in one place." : locale === "fa" ? "تنظیمات دوکان، اندازه‌های لباس و انتخاب‌های دیزاین را در یک بخش مدیریت کنید." : "د دوکان تنظیمات، د لباس اندازې او د ډیزاین انتخابونه په یوه برخه کې اداره کړئ.";
  return <div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-xl font-semibold">{t.settingAndGarmentConfiguration}</h1><p className="text-sm text-slate-500">{help}</p></div>
    {shop && <section><h2 className="mb-3 text-base font-semibold">{t.shopSettingsTitle}</h2><SettingsForm shopName={shop.shopName} address={shop.address} phone={shop.phone} email={shop.email} currency={shop.currency} taxPercent={shop.taxPercent} logoUrl={shop.logoUrl} translations={t} /></section>}
    <section><h2 className="mb-3 text-base font-semibold">{t.garmentConfigurationTitle}</h2>
    <div className="grid gap-5 lg:grid-cols-3">
      <form action={addGarmentType} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">{t.addGarmentType}</h2><input required name="code" placeholder={t.code} className="w-full rounded border p-2" /><input required name="nameFa" placeholder={t.labelFa} className="w-full rounded border p-2" /><input required name="namePs" placeholder={t.labelPs} className="w-full rounded border p-2" /><button className="rounded bg-slate-900 px-3 py-2 text-sm text-white">+</button></form>
      <form action={addMeasurementField} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">{t.addMeasurementField}</h2><select required name="garmentTypeId" className="w-full rounded border p-2"><option value="">{t.garmentType}</option>{types.map((type) => <option key={type.id} value={type.id}>{locale === "ps" ? type.namePs : type.nameFa}</option>)}</select><input required name="code" placeholder={t.code} className="w-full rounded border p-2" /><input required name="labelFa" placeholder={t.labelFa} className="w-full rounded border p-2" /><input required name="labelPs" placeholder={t.labelPs} className="w-full rounded border p-2" /><input name="unit" defaultValue="inch" placeholder={t.unit} className="w-full rounded border p-2" /><label className="text-sm"><input name="isRequired" type="checkbox" /> {t.required}</label><button className="block rounded bg-slate-900 px-3 py-2 text-sm text-white">+</button></form>
      <form action={addDesignOption} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">{t.addDesignOption}</h2><select required name="garmentTypeId" className="w-full rounded border p-2"><option value="">{t.garmentType}</option>{types.map((type) => <option key={type.id} value={type.id}>{locale === "ps" ? type.namePs : type.nameFa}</option>)}</select><select name="categoryId" className="w-full rounded border p-2"><option value="">{t.newDesignCategory}</option>{categories.map((category) => <option key={category.id} value={category.id}>{locale === "ps" ? category.labelPs : category.labelFa}</option>)}</select><input name="categoryFa" placeholder={`${t.designCategories} (${t.labelFa})`} className="w-full rounded border p-2" /><input name="categoryPs" placeholder={`${t.designCategories} (${t.labelPs})`} className="w-full rounded border p-2" /><input required name="labelFa" placeholder={`${t.designOptions} (${t.labelFa})`} className="w-full rounded border p-2" /><input required name="labelPs" placeholder={`${t.designOptions} (${t.labelPs})`} className="w-full rounded border p-2" /><button className="rounded bg-slate-900 px-3 py-2 text-sm text-white">+</button></form>
    </div>
    <section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">{t.saved ?? "Saved"}</h2><div className="space-y-4">{types.map((type) => <div key={type.id} className="rounded-lg bg-slate-50 p-3"><strong>{locale === "ps" ? type.namePs : type.nameFa}</strong><div className="mt-2 flex flex-wrap gap-2 text-xs">{fields.filter((field) => field.garmentTypeId === type.id).map((field) => <span key={field.id} className="rounded bg-white px-2 py-1">{locale === "ps" ? field.labelPs : field.labelFa}</span>)}{categories.filter((category) => category.garmentTypeId === type.id).flatMap((category) => options.filter((option) => option.categoryId === category.id).map((option) => <span key={option.id} className="rounded border border-indigo-200 bg-indigo-50 px-2 py-1">{locale === "ps" ? option.labelPs : option.labelFa}</span>))}</div></div>)}</div></section>
    </section>
  </div>;
}
