import { deliverReadyOrder } from "@/app/actions/garment-management";
import { customers, db, tailorOrderItems, tailorOrders } from "@/lib/db";
import { eq } from "drizzle-orm";
import { cookies } from "next/headers";
import { getLocale } from "@/lib/i18n";

export default async function DeliveryPage() {
  const locale = getLocale((await cookies()).get("tailor_locale")?.value);
  const rows = await db.select({ itemId: tailorOrderItems.id, ticketNo: tailorOrderItems.ticketNo, itemAmount: tailorOrderItems.itemAmount, orderId: tailorOrders.id, orderNo: tailorOrders.orderNo, customer: customers.name, phone: customers.phone, total: tailorOrders.totalAmount, paid: tailorOrders.advancePaid, due: tailorOrders.balanceDue, promisedDate: tailorOrders.promisedDate }).from(tailorOrderItems).innerJoin(tailorOrders, eq(tailorOrders.id, tailorOrderItems.tailorOrderId)).innerJoin(customers, eq(customers.id, tailorOrders.customerId)).where(eq(tailorOrderItems.currentStage, "ready"));
  const text = locale === "ps" ? { title: "د جامو سپارل", ticket: "ټکټ", customer: "پېرېدونکی", due: "پاتې پیسې", collect: "اوس ترلاسه شوې", deliver: "سپارل", receipt: "رسید PDF" } : { title: "تحویل لباس", ticket: "شماره لباس", customer: "مشتری", due: "باقی‌مانده", collect: "دریافت فعلی", deliver: "تحویل", receipt: "رسید PDF" };
  return <div className="space-y-5"><div><h1 className="text-xl font-semibold">{text.title}</h1><p className="text-sm text-slate-500">{locale === "ps" ? "لباس چمتو دی؛ پیسې ثبت کړئ او رسید واخلئ." : "لباس آماده است؛ پرداخت را ثبت کنید و رسید بگیرید."}</p></div><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs"><tr><th className="p-3">{text.ticket}</th><th>{text.customer}</th><th>{text.due}</th><th className="p-3"></th></tr></thead><tbody>{rows.map((row) => <tr key={row.itemId} className="border-t"><td className="p-3 font-medium">{row.ticketNo}</td><td>{row.customer}<div className="text-xs text-slate-400">{row.phone}</div></td><td>{Number(row.due).toFixed(2)} AFN</td><td className="p-3"><form action={deliverReadyOrder} className="flex flex-wrap items-center justify-end gap-2"><input type="hidden" name="garmentItemId" value={row.itemId}/><input name="balanceCollected" min="0" max={row.due} step="0.01" type="number" defaultValue="0" className="w-24 rounded border p-1" title={text.collect}/><select name="paymentMethod" className="rounded border p-1"><option value="cash">Cash</option><option value="bank">Bank</option></select><button className="rounded bg-emerald-700 px-2 py-1 text-white">{text.deliver}</button><a className="text-xs underline" target="_blank" href={`/api/tailor-orders/${row.orderId}/pdf`}>{text.receipt}</a></form></td></tr>)}</tbody></table></div></div>;
}
