import { approveQuality, assignWorker, completeWorkerAssignment } from "@/app/actions/garment-management";
import { businessContacts, db, tailorOrderItems, workerAssignments } from "@/lib/db";
import { desc, eq, sql } from "drizzle-orm";
import { cookies } from "next/headers";
import { getLocale } from "@/lib/i18n";

export default async function StitchingCuttingPage() {
  const locale = getLocale((await cookies()).get("tailor_locale")?.value);
  const [items, assignments, workers] = await Promise.all([db.select().from(tailorOrderItems).orderBy(desc(tailorOrderItems.updatedAt)), db.select().from(workerAssignments).orderBy(desc(workerAssignments.assignedAt)), db.select().from(businessContacts).where(sql`${businessContacts.roles} ?| array['tailor','cutter']`)]);
  const text = locale === "ps" ? { title: "ګنډل او پرې کول", cutter: "قیچي کوونکی", tailor: "خیاط", assign: "سپارل", complete: "بشپړ", quality: "کیفیت تایید", rate: "اجرت", garment: "جامه" } : { title: "دوخت و برش", cutter: "برش‌کار", tailor: "خیاط", assign: "سپردن", complete: "تکمیل", quality: "تأیید کیفیت", rate: "اجرت", garment: "لباس" };
  const activeAssignment = new Set(assignments.filter((assignment) => assignment.status === "assigned").map((assignment) => assignment.garmentItemId));
  return <div className="space-y-6"><h1 className="text-xl font-semibold">{text.title}</h1><div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border bg-white p-4"><h2 className="mb-3 font-semibold">{text.cutter}</h2>{items.filter((item) => ["measurement","fabric_ready","cutting"].includes(item.currentStage) && !activeAssignment.has(item.id)).map((item) => <AssignmentForm key={item.id} itemId={item.id} ticket={item.ticketNo} workers={workers.filter((worker) => (worker.roles as string[]).includes("cutter"))} type="cutter" text={text} />)}</section><section className="rounded-xl border bg-white p-4"><h2 className="mb-3 font-semibold">{text.tailor}</h2>{items.filter((item) => ["cutting_done","stitching"].includes(item.currentStage) && !activeAssignment.has(item.id)).map((item) => <AssignmentForm key={item.id} itemId={item.id} ticket={item.ticketNo} workers={workers.filter((worker) => (worker.roles as string[]).includes("tailor"))} type="tailor" text={text} />)}</section></div><section className="rounded-xl border bg-white p-4"><h2 className="mb-3 font-semibold">{locale === "ps" ? "روان کار" : "کارهای جاری"}</h2>{assignments.filter((assignment) => assignment.status === "assigned").map((assignment) => <form key={assignment.id} action={completeWorkerAssignment} className="flex items-center justify-between border-t py-2 text-sm"><span>{assignment.workType} · {assignment.garmentItemId} · {Number(assignment.agreedRate).toFixed(2)} AFN</span><input type="hidden" name="assignmentId" value={assignment.id} /><button className="rounded bg-emerald-700 px-3 py-1 text-white">{text.complete}</button></form>)}{items.filter((item) => item.currentStage === "quality_check").map((item) => <form key={`quality-${item.id}`} action={approveQuality} className="flex items-center justify-between border-t py-2 text-sm"><span>{item.ticketNo}</span><input type="hidden" name="garmentItemId" value={item.id} /><button className="rounded bg-indigo-700 px-3 py-1 text-white">{text.quality}</button></form>)}</section></div>;
}

function AssignmentForm({ itemId, ticket, workers, type, text }: { itemId: number; ticket: string; workers: { id: number; name: string }[]; type: "cutter" | "tailor"; text: { assign: string; rate: string } }) {
  return <form action={assignWorker} className="mb-2 flex flex-wrap items-center gap-2 rounded bg-slate-50 p-2 text-sm"><span className="min-w-28 font-medium">{ticket}</span><input type="hidden" name="garmentItemId" value={itemId} /><input type="hidden" name="workType" value={type} /><select required name="businessContactId" className="rounded border p-1"><option value="">—</option>{workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select><input required name="agreedRate" min="0" step="0.01" type="number" placeholder={text.rate} className="w-24 rounded border p-1"/><button className="rounded bg-slate-900 px-2 py-1 text-white">{text.assign}</button></form>;
}
