import { addStorageLocation, storeGarment } from "@/app/actions/garment-management";
import { db, garmentStorageAssignments, storageLocations, tailorOrderItems } from "@/lib/db";
import { and, eq, isNull, sql } from "drizzle-orm";
import { requireSession } from "@/lib/auth/get-session";
import { cookies } from "next/headers";
import { getLocale } from "@/lib/i18n";

export default async function CabinetPage() {
  const session = await requireSession(); const locale = getLocale((await cookies()).get("tailor_locale")?.value);
  const [locations, readyItems] = await Promise.all([db.select().from(storageLocations).where(eq(storageLocations.branchId, session.branchId)), db.select().from(tailorOrderItems).where(eq(tailorOrderItems.currentStage, "ready"))]);
  const usage = await db.execute<{ storage_location_id: number; garments: string; orders: string }>(sql`SELECT assignment.storage_location_id, COUNT(*) AS garments, COUNT(DISTINCT item.tailor_order_id) AS orders FROM garment_storage_assignments assignment JOIN tailor_order_items item ON item.id = assignment.garment_item_id WHERE assignment.removed_at IS NULL GROUP BY assignment.storage_location_id`);
  const freeItems = [] as typeof readyItems;
  for (const item of readyItems) { const [stored] = await db.select({ id: garmentStorageAssignments.id }).from(garmentStorageAssignments).where(and(eq(garmentStorageAssignments.garmentItemId, item.id), isNull(garmentStorageAssignments.removedAt))); if (!stored) freeItems.push(item); }
  const text = locale === "ps" ? { title: "د جامو المارۍ", add: "نوې خانه", store: "جامه کېښودل", garment: "چمتو جامه", location: "خانه", capacity: "ظرفیت", garments: "جامې", orders: "فرمایشونه" } : { title: "الماری لباس‌ها", add: "افزودن خانه", store: "گذاشتن لباس", garment: "لباس آماده", location: "خانه", capacity: "ظرفیت", garments: "لباس", orders: "فرمایش‌ها" };
  return <div className="space-y-6"><div><h1 className="text-xl font-semibold">{text.title}</h1><p className="text-sm text-slate-500">{locale === "ps" ? "د هرې خانې د جامو او فرمایشونو ظرفیت وڅارئ." : "ظرفیت لباس‌ها و فرمایش‌ها را در هر خانه پیگیری کنید."}</p></div><div className="grid gap-4 md:grid-cols-2"><form action={addStorageLocation} className="flex flex-wrap items-end gap-2 rounded-xl border bg-white p-4"><label className="text-sm">{text.location}<input required name="code" placeholder="C1" className="ms-2 w-20 rounded border p-2" /></label><label className="text-sm">{text.garments}<input name="capacityGarments" defaultValue="20" type="number" className="ms-2 w-16 rounded border p-2" /></label><label className="text-sm">{text.orders}<input name="capacityOrders" defaultValue="10" type="number" className="ms-2 w-16 rounded border p-2" /></label><button className="rounded bg-slate-900 px-3 py-2 text-sm text-white">{text.add}</button></form><form action={storeGarment} className="flex flex-wrap items-end gap-2 rounded-xl border bg-white p-4"><select required name="garmentItemId" className="rounded border p-2"><option value="">{text.garment}</option>{freeItems.map((item) => <option key={item.id} value={item.id}>{item.ticketNo}</option>)}</select><select required name="storageLocationId" className="rounded border p-2"><option value="">{text.location}</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.code}</option>)}</select><button className="rounded bg-emerald-700 px-3 py-2 text-sm text-white">{text.store}</button></form></div><section className="grid grid-cols-2 gap-4 md:grid-cols-5">{locations.map((location) => { const current = usage.find((row) => row.storage_location_id === location.id); const garments = Number(current?.garments ?? 0); const orders = Number(current?.orders ?? 0); const full = garments >= location.capacityGarments || orders >= location.capacityOrders; return <div key={location.id} className={`rounded-xl border p-4 ${full ? "border-red-200 bg-red-50" : "bg-white"}`}><div className="text-lg font-bold">{location.code}</div><div className="mt-2 text-xs text-slate-600">{garments}/{location.capacityGarments} {text.garments}</div><div className="text-xs text-slate-600">{orders}/{location.capacityOrders} {text.orders}</div></div>; })}</section></div>;
}
